language: scala
sudo: false
jdk:
- oraclejdk8
dist: trusty
env:
  global:
  - TRAVIS_SBT_VERSION="1.2.8"
  - secure: wundCOH+/rOVD5KqGskdSPKfJAb8I77IN2/SV/Z9icosN667OduUfpr6of0IuIYXFUDSuz53UQl9wxtAZctG1lCnYslmolTuZUvbeMn+bhbKQpK6QzzfOlyN3JJdSvdET9jRP2VDGMO1LB1TBZRDBEdXf1XUfVHhCERkI9DMaeQqt2EU4kWBzdQ3BJH2Fk3cuKlxZzy4/MlkOE4k0Lf30B3c/g1V0DVxbW1Q9MThi5tquKQ8KHmDlZTYeVqBPZm5dfqEUjHMxV86M++tYiVzXj/8Nkmtb9nt65d/Q3of9Zz0okR/nFbqmjZGmsPO3nJDdt3n7vPYAJvlM71rqtjQRSBxkrrKHOcPzFQ4l5roQEfHsmQKJJLEVt+utjvkXpswh3mapCJjUfB+eVYOLGc+Gg61D52LDGEtHw8oBdB0pHQ0lD6HPNNQauWM4TvaeeuTS6/Oc1cuqvkIOwrBnnqoJo1gDYAehguEQSUg6uES40odF0pnnnWWYlYS9AKeyRp6PLhRB9JWgAbxc5kClz6KTZoS8VTXK0IP4ytMCzWQiS2EhSX+RUlGDa702Q2b+suDay/Tp4RpmdKNXvef2uuRf0mHpUVSvo5rmnQGZBGvJboe332pPNab0vdap6wYbOeq9NZ7ayWy+037vAwdv2i1OCnMof8n11nl76m6vhVDKM0=
  - secure: AfzQSeED577inTOpFyEe8Hu7yzSs+k/nANOZUXFXHFLa2MJZWiKMpY0NtqZtBu5knjugRJna/0Jpo3QfoZ30+FFyh5HUMKSLD/DL7n6SogqXTOmij9otG/i63gEh6M/jNRY87ZHB1Fb9S4uLPWyb1Z/BQ0oKhmAUnjTkOW6Ua576PbVY/9nEM0qJRBRnHKp2l6LKnCiwzFH95a5r88ua5GHqn1FFPxkFa54qN3oGgFj+f66dV76CvwFatVz6hrRVb9LryVlbrAiOdpG5waGay5Sf7Goepr9xnHWRbms/1S0Q1q+1uy1QMmAK8Q7JFYN+C0bzIxbnj7X/WDn/SCY8HaL1JX2lSJq1xl9+fosGHh1IeGVLcwGvkpsewLBdDnsq/Jycm6ihoNzFNluYa3kNuCQ728Qs0DTL1OBnR8C5GpSRvWJP9Q8cPxJEEYe/8rUVaYVEQ78SUGjJ6mpdC/VRnFvTv4ZzDYbAA5XUL74k42SKsTyQjjMbxv5pdPYHDMql4JJ/2fTmud2w3x+mftutIUChQ/nhyKm4yE2nypMsZ6rFicjMcPoxnR4oGhtHRSs6JhwvuTwhutffEfLTArsgIwvIrATlZM38z0hiOLUDRgcUIKpzSlLElIqCbF/LV9EORJNeERtwGHbOrg7Kur3D3kPOWCDDrfzCHR8Og4psUD4=
before_install:
- nvm install 12 &&
  nvm use 12
- node --version &&
  npm --version
script:
- sbt clean coverage test &&
  sbt coverageAggregate coveralls &&
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" -o "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then
    if [ -z "$TRAVIS_TAG" ]; then
      echo "Publish todos to expo";
      sbt "project project scommons-examples-mobile-todos-expo" clean fullOptJS;
      cd todos/expo;
      npm install;
      expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD;
      EXPO_ENV=production expo publish --non-interactive;

      cd ../..;
      echo "Publish starwars to expo";
      sbt "project project scommons-examples-mobile-starwars-app" clean fullOptJS;
      cd starwars/app;
      npm install;
      expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD;
      EXPO_ENV=production expo publish --non-interactive;
    else
      echo "Publish a release version=$TRAVIS_TAG";
    fi
  else
    echo "This is not a master branch commit. Skipping the publish/release step";
  fi
cache:
  directories:
  - ~/.npm
  - ~/.nvm
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
