language: scala
sudo: false
jdk:
- oraclejdk8
dist: trusty
env:
  global:
  - TRAVIS_SBT_VERSION="1.2.8"
before_install:
- nvm install 12 &&
  nvm use 12
- node --version &&
  npm --version
script:
- sbt clean coverage test &&
  sbt coverageAggregate coveralls
cache:
  directories:
  - ~/.npm
  - ~/.nvm
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
