name: CI

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout (merge)
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0

      - name: Git checkout (PR)
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          # see: https://frontside.com/blog/2020-05-26-github-actions-pull_request/#how-does-pull_request-affect-actionscheckout
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'sbt'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.nvm
            ~/work/scommons-examples-mobile/scommons-examples-mobile/starwars/app/node_modules
            ~/work/scommons-examples-mobile/scommons-examples-mobile/starwars/app/package-lock.json
            ~/work/scommons-examples-mobile/scommons-examples-mobile/starwars/app/target/scala-2.13/scalajs-bundler/main/node_modules
            ~/work/scommons-examples-mobile/scommons-examples-mobile/starwars/app/target/scala-2.13/scalajs-bundler/main/package-lock.json
            ~/work/scommons-examples-mobile/scommons-examples-mobile/starwars/app/target/scala-2.13/scalajs-bundler/test/node_modules
            ~/work/scommons-examples-mobile/scommons-examples-mobile/starwars/app/target/scala-2.13/scalajs-bundler/test/package-lock.json
            ~/work/scommons-examples-mobile/scommons-examples-mobile/todos/expo/node_modules
            ~/work/scommons-examples-mobile/scommons-examples-mobile/todos/expo/package-lock.json
            ~/work/scommons-examples-mobile/scommons-examples-mobile/todos/expo/target/scala-2.13/scalajs-bundler/main/node_modules
            ~/work/scommons-examples-mobile/scommons-examples-mobile/todos/expo/target/scala-2.13/scalajs-bundler/main/package-lock.json
            ~/work/scommons-examples-mobile/scommons-examples-mobile/todos/expo/target/scala-2.13/scalajs-bundler/test/node_modules
            ~/work/scommons-examples-mobile/scommons-examples-mobile/todos/expo/target/scala-2.13/scalajs-bundler/test/package-lock.json
            ~/work/scommons-examples-mobile/scommons-examples-mobile/todos/app/target/scala-2.13/scalajs-bundler/test/node_modules
            ~/work/scommons-examples-mobile/scommons-examples-mobile/todos/app/target/scala-2.13/scalajs-bundler/test/package-lock.json
            ~/work/scommons-examples-mobile/scommons-examples-mobile/todos/bare/target/scala-2.13/scalajs-bundler/test/node_modules
            ~/work/scommons-examples-mobile/scommons-examples-mobile/todos/bare/target/scala-2.13/scalajs-bundler/test/package-lock.json
          key: ${{ runner.os }}-node_modules-cache-v3-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-cache-v3-

      - name: Run tests
        run: |
          sbt coverage test
          sbt coverageAggregate coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Publish todos to expo
        run: |
          sbt clean
          sbt "project scommons-examples-mobile-todos-expo" fullOptJS
          cd todos/expo
          npm install
          npm install expo-cli@6 --save-dev
          ./node_modules/expo-cli/bin/expo.js login -u $EXPO_USERNAME -p $EXPO_PASSWORD
          NODE_OPTIONS=--max_old_space_size=4096 EXPO_ENV=production ./node_modules/expo-cli/bin/expo.js publish --non-interactive
        if: ${{ !github.event.pull_request }}
        env:
          EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}

      - name: Publish starwars to expo
        run: |
          sbt clean
          sbt "project scommons-examples-mobile-starwars-app" fullOptJS
          cd starwars/app
          npm install
          npm install expo-cli@6 --save-dev
          ./node_modules/expo-cli/bin/expo.js login -u $EXPO_USERNAME -p $EXPO_PASSWORD
          NODE_OPTIONS=--max_old_space_size=4096 EXPO_ENV=production ./node_modules/expo-cli/bin/expo.js publish --non-interactive
        if: ${{ !github.event.pull_request }}
        env:
          EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
